### ISSUE TITLE
linear search

### ISSUE THREAD

**Issue by AkashMittal-30** [AkashMittal-30/C-Components#1]
write c++ code for linear search

**Comment by shri05-stack** [comment]
Please assign me this issue. I am very good at competitive programming. I make sure you don't feel regreat after assigning me this task.

**Comment by Saurav-Sutaria** [comment]
Hey @AkashMittal-30 I have added Linear Search code in c++, please review my PR.

**Comment by AkashMittal-30** [comment]
> Please assign me this issue. I am very good at competitive programming. I make sure you don't feel regreat after assigning me this task.

@shri05-stack  sorry, I saw your request late. I have assigned you a different issue, you can work on it.

**Comment by AkashMittal-30** [comment]
> Hey @AkashMittal-30 I have added Linear Search code in c++, please review my PR.

Good work,
Do write comments in your future contributions!!
